<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.89" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nadlan.Core\Nadlan.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Sql\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nadlan.Core.Tests" />
  </ItemGroup>

</Project>
